import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Default from '../components/Default'
import { useState } from 'react'
import Location from '../components/Location'
import axios from 'axios'
export default function Home() {

  const [location, setLocation] = useState(false)
  const [locationValue, setLocationValue] = useState("")
  const [weatherData, setWeatherData] = useState(null)
  const handleSubmit = async (e) => {
    e.preventDefault()
    const locationRes = await axios.get(`//dataservice.accuweather.com/locations/v1/cities/search?apikey=%09QzeKute5GSXAOUVQSY3orxdxaa6LoAhV&q=${locationValue}`)
    const locationData  = locationRes.data;
    const  key  = locationData[0]["Key"]
    const res = await axios.get(`//dataservice.accuweather.com/forecasts/v1/daily/5day/${key}?apikey=QzeKute5GSXAOUVQSY3orxdxaa6LoAhV&metric=true`)
    const { data } = res;
    const newData = { ...data, location: locationValue}
    setWeatherData(newData)
    setLocation(true)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.searchArea}>
          <h1 className={styles.heading}>Weather App</h1>
          <form action="" className={styles.form} onSubmit={handleSubmit}>
            <input type="text" className={styles.weatherInput} required placeholder='enter location' value={locationValue}
              onChange={(e) => { setLocationValue(e.target.value) }} />
            <button type='submit' className={styles.searchBtn}>Search</button>
          </form>
        </div>
        <div className={styles.weatherArea}>
          {(location && weatherData) ? <Location data={weatherData} /> : <Default />}
        </div>
      </main>
    </div>
  )
}
